/**
 * DTNP Protocol Constants
 */

export const DTNP_VERSION = '0.1.0';

// Message types
export const MSG = {
  TUNNEL_REQUEST: 'TUNNEL_REQUEST',
  TUNNEL_OFFER: 'TUNNEL_OFFER',
  TUNNEL_ACCEPT: 'TUNNEL_ACCEPT',
  TUNNEL_ESTABLISHED: 'TUNNEL_ESTABLISHED',
  TUNNEL_HEARTBEAT: 'TUNNEL_HEARTBEAT',
  TUNNEL_TEARDOWN: 'TUNNEL_TEARDOWN',
  TUNNEL_REJECTED: 'TUNNEL_REJECTED',
  TUNNEL_ERROR: 'TUNNEL_ERROR',
  TUNNEL_CONFIG_UPDATE: 'TUNNEL_CONFIG_UPDATE',
  TUNNEL_MAINTENANCE_NOTICE: 'TUNNEL_MAINTENANCE_NOTICE',
};

// Tunnel types
export const TUNNEL_TYPES = {
  WIREGUARD: 'wireguard',
  SSH_TUN: 'ssh-tun',
  SSH_REVERSE: 'ssh-reverse',
};

// Transport types
export const TRANSPORT_TYPES = {
  UDP: 'udp',
  WSS: 'wss',
  WSS_PROXY: 'wss-proxy',
  AUTO: 'auto',
};

// Client states
export const CLIENT_STATE = {
  IDLE: 'IDLE',
  BOOTSTRAPPING: 'BOOTSTRAPPING',
  NEGOTIATING: 'NEGOTIATING',
  ESTABLISHING: 'ESTABLISHING',
  ACTIVE: 'ACTIVE',
  RECONNECTING: 'RECONNECTING',
  TEARING_DOWN: 'TEARING_DOWN',
};

// Teardown reasons
export const TEARDOWN_REASONS = {
  GRACEFUL_SHUTDOWN: 'GRACEFUL_SHUTDOWN',
  TIMEOUT: 'TIMEOUT',
  ERROR: 'ERROR',
  EVICTION: 'EVICTION',
  CERTIFICATE_EXPIRY: 'CERTIFICATE_EXPIRY',
  TUNNEL_FAILURE: 'TUNNEL_FAILURE',
  SERVER_MAINTENANCE: 'SERVER_MAINTENANCE',
};

// Error codes
export const ERR = {
  VERSION_MISMATCH: 'ERR_VERSION_MISMATCH',
  ACL_DENIED: 'ERR_ACL_DENIED',
  DOMAIN_UNAUTHORIZED: 'ERR_DOMAIN_UNAUTHORIZED',
  DOMAIN_CONFLICT: 'ERR_DOMAIN_CONFLICT',
  DOMAIN_INVALID: 'ERR_DOMAIN_INVALID',
  CAPACITY: 'ERR_CAPACITY',
  POOL_EXHAUSTED: 'ERR_POOL_EXHAUSTED',
  UNSUPPORTED_TUNNEL: 'ERR_UNSUPPORTED_TUNNEL',
  RATE_LIMITED: 'ERR_RATE_LIMITED',
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  TUNNEL_HEALTH_FAILED: 'ERR_TUNNEL_HEALTH_FAILED',
  UNKNOWN_MESSAGE_TYPE: 'ERR_UNKNOWN_MESSAGE_TYPE',
  SEQUENCE_REPLAY: 'ERR_SEQUENCE_REPLAY',
  TIMESTAMP_SKEW: 'ERR_TIMESTAMP_SKEW',
  SIGNATURE_MISMATCH: 'ERR_SIGNATURE_MISMATCH',
  SESSION_CONFLICT: 'ERR_SESSION_CONFLICT',
  CONFIG_UPDATE_FAILED: 'ERR_CONFIG_UPDATE_FAILED',
};

// Timeouts (milliseconds)
export const TIMEOUTS = {
  NEGOTIATE: 90_000,
  ESTABLISH: 120_000,
  ACCEPT: 30_000,
  OFFER_TTL: 180_000,
  HANDSHAKE_STALE: 180_000,       // 3 minutes - client considers degraded
  RECONNECT_WINDOW: 300_000,      // 5 minutes - max reconnect attempt time
  HEARTBEAT_INTERVAL: 900_000,    // 15 minutes
  TIMESTAMP_SKEW: 120_000,        // 2 minutes
  MESSAGE_BUFFER: 10_000,         // 10 seconds for out-of-order buffering
  WG_HANDSHAKE_CHECK: 30_000,     // 30 seconds between handshake checks
};

// Retry policy
export const RETRY = {
  REQUEST_BASE_S: 10,
  REQUEST_CAP_S: 120,
  REQUEST_MAX: 3,
  ACCEPT_BASE_S: 5,
  ACCEPT_CAP_S: 30,
  ACCEPT_MAX: 2,
  RECONNECT_BASE_S: 10,
  RECONNECT_CAP_S: 60,
  RECONNECT_MAX: 3,
};

// Exit codes
export const EXIT_CODES = {
  SUCCESS: 0,
  NEGOTIATION_FAILED: 15,
  TUNNEL_FAILED: 16,
  DNS_TIMEOUT: 17,
};

// Default relay URLs
export const DEFAULT_RELAY_URLS = [
  'wss://relay.primal.net',
  'wss://relay.damus.io',
  'wss://nos.lol',
  'wss://relay.nostr.band',
];
